name: task_2
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_sign_in: ^5.4.2
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  cloud_firestore: ^4.2.0
  get: ^4.6.5
  sqflite: ^2.2.2
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/